
export const userConstant = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGOUT: 'USERS_LOGOUT',
    SERVER_ERROR: 'SERVER_ERROR_GET',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    REGISTER: 'USERS_REGISTER',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE'
};

/* start coding for role management type */

export const role = {
    DATABASE_TABLE: 'ROLE_DATABASE_TABLE',
    ROLEERROR: 'ROLE_ERROR',
    GET_DOG: 'GET_DOG'
}
/* start coding for Permission Management*/

export const permission = {
    GET_PERMISSION: 'GET_ALL_PERMISSION_DATA',
    ADD_PERMISSION: 'ADD_NEW_PERMISSION',
    PERMISSION_BY_ID: 'PERMISSION_BY_ID',
    EDIT_PERMISSION: 'EDIT_PERMISSION',
    UPDATE_PERMISSION: 'UPDATE_PERMISSION',
    DELETE_PERMISSION: 'DELETE_PERMISSION'
}
